# No configuration value is mandatory, those uncommented are just those needed
# to run with the current repository layout.
# Not even the file itself is mandatory, if not present, root is simply set to
# $PWD.
# Values specified (both uncommented and commented) are defaults, if not
# explicitly declared to be different.

[paths]
# paths relative to the location of this file
runcards = "pinecards"
results = "results"
# theories = "theories"
# prefix = ".prefix"
# bin = ".prefix/bin"
# lib = ".prefix/lib"
# mg5amc = ".prefix/mg5amc"
# pineappl = ".prefix/pineappl"
# cargo = ".prefix/cargo"
# lhapdf = ".prefix/lhapdf"
# lhapdf_data_alternative = ".prefix/share/LHAPDF"

[commands]
# mg5 =  ".prefix/mg5amc/bin/mg5_aMC"
# vrap = ".prefix/bin/Vrap"
# pineappl = ".prefix/bin/pineappl"
